### ISSUE TITLE
SnpRecode does not work with Python version 3.11

### ISSUE THREAD

**Issue by soda460** [AMarete/fimpute-utils#2]
Hi Andrew,

I hope you are doing well!

Currently, SnpRecode does not work with Python version 3.11 likely because 3.11 < 3.6.

At present, I do not known how I can re-build the executable from source. That would be great If you can fix this small issue!

Best regards,

Jean-Simon from AAFC

**Comment by AMarete** [comment]
Hi Jean-Simon,
Thanks for noticing the bug. I have added a new version of SnpRecode which
should hopefully resolve this issue. If it persists, however, let me know.

Andrew

**Comment by AMarete** [comment]
Hi Jean-Simon,
Thanks for noticing the bug. I have added a new version of SnpRecode which should hopefully resolve this issue. If it persists, however, let me know.

Andrew
