### ISSUE TITLE
Seems like FImpute has been expired

### ISSUE THREAD

**Issue by Serfentum** [AMarete/fimpute-utils#3]
Hi!
Thank you for your work, I'd like to use fimpute and your tool, but unfortunately fimpute I had loaded from official site is expired( Can you share working fimpute binary or its source code?

**Comment by AMarete** [comment]
Hi, you have to contact the [FImpute authors](https://animalbiosciences.uoguelph.ca/~msargol/fimpute/) to get a working copy of the software.
